Repository woowacourse-teams/2024-chongdae-market, pull requests merged in 2024-10, with the labels that each got.

#556 feat: Offering 쿼리에 Native Query 적용(+ 테스트 코드 수정)
  backend/src/main/java/com/zzang/chongdae/comment/service/CommentService.java
  backend/src/main/java/com/zzang/chongdae/offering/repository/OfferingRepository.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
  backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
  backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java
Labels: feature, 💻 BE

#558 fix: Native Query 미반영 서비스 코드 수정
  backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
Labels: bug/error, 💻 BE

#586 refactor: 스케줄링 시점 수정
  backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
  backend/src/main/java/com/zzang/chongdae/scheduler/service/SchedulerService.java
  backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
Labels: refactor, 💻 BE

#588 feat: 채팅 view type 관리 및 날짜 view 추가
  android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailActivity.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/CommentDetailViewModel.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/adapter/comment/CommentAdapter.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/adapter/comment/CommentViewType.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/adapter/comment/DateSeparatorViewHolder.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/event/CommentDetailEvent.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/commentdetail/event/OnUpdateStatusClickListener.kt
  android/app/src/main/res/layout/dialog_update_status.xml
  android/app/src/main/res/layout/item_date_separator.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  backend/src/test/java/com/zzang/chongdae/ChongdaeApplicationTests.java
Labels: 📱 AN
