Repository woowacourse-teams/2024-chongdae-market, pull requests merged in 2025-03, with the labels that each got.

#703 feat: 참여 시 물품 개수 필드 추가
  backend/src/main/java/com/zzang/chongdae/offering/exception/OfferingErrorCode.java
  backend/src/main/java/com/zzang/chongdae/offering/repository/entity/OfferingEntity.java
  backend/src/main/java/com/zzang/chongdae/offering/service/OfferingService.java
  backend/src/main/java/com/zzang/chongdae/offering/service/dto/OfferingSaveRequest.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/domain/OfferingMembers.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/exception/OfferingMemberErrorCode.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/repository/entity/OfferingMemberEntity.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/OfferingMemberService.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantResponse.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipantResponseItem.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ParticipationRequest.java
  backend/src/main/java/com/zzang/chongdae/offeringmember/service/dto/ProposerResponseItem.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/zzang/chongdae/global/domain/OfferingMemberFixture.java
  backend/src/test/java/com/zzang/chongdae/offering/integration/OfferingIntegrationTest.java
  backend/src/test/java/com/zzang/chongdae/offering/service/OfferingServiceTest.java
  backend/src/test/java/com/zzang/chongdae/offeringmember/integration/OfferingMemberIntegrationTest.java
  backend/src/test/java/com/zzang/chongdae/offeringmember/service/OfferingMemberServiceConcurrencyTest.java
Labels: feature, 💻 BE

#706 refactor: 홈화면 compose migration 작업
  android/.editorconfig
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/zzang/chongdae/presentation/view/home/OfferingFiltersTest.kt
  android/app/src/androidTest/java/com/zzang/chongdae/presentation/view/home/OfferingItemTest.kt
  android/app/src/androidTest/java/com/zzang/chongdae/presentation/view/home/OfferingSearchBarTest.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/util/BindingAdapters.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/HomeFragment.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnFilterClickListener.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OnFloatingClickListener.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingAdapter.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/adapter/OfferingViewHolder.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/HomeScreen.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingFilters.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingFiltersState.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingItem.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingSearchBar.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingSearchState.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/component/OfferingsList.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_offering.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: refactor, 📱 AN

#716 feat: 상세화면 상품 구매 갯수 선택 기능 추가
  android/app/src/main/java/com/zzang/chongdae/data/remote/dto/request/ParticipationRequest.kt
  android/app/src/main/java/com/zzang/chongdae/data/repository/OfferingDetailRepositoryImpl.kt
  android/app/src/main/java/com/zzang/chongdae/domain/repository/OfferingDetailRepository.kt
  android/app/src/main/java/com/zzang/chongdae/domain/usecase/offeringdetail/SaveParticipationUseCase.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/home/OfferingViewModel.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailFragment.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/OfferingDetailViewModel.kt
  android/app/src/main/java/com/zzang/chongdae/presentation/view/offeringdetail/bottomsheet/OfferingDetailBottomSheetDialog.kt
  android/app/src/main/res/drawable/bg_bottom_sheet_dialog.xml
  android/app/src/main/res/drawable/bg_gray300_radius_5dp.xml
  android/app/src/main/res/drawable/bg_main_color_radius_10dp.xml
  android/app/src/main/res/drawable/bg_main_color_radius_18dp.xml
  android/app/src/main/res/layout/dialog_offering_detail_bottom_sheet.xml
  android/app/src/main/res/layout/fragment_offering_detail.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
Labels: feature, 📱 AN
